### ISSUE TITLE
Dev Dependencies broken in node v6

### ISSUE THREAD

**Issue by chenyulun** [marionettejs/backbone.marionette#3205]
English is very poor！！sorry！

TypeError: Error transforming /Users/tusm/github/backbone.marionette-master/src/backbone.marionette.js with 'babel' plugin: Path must be a string. Received undefined
    at assertPath

import preset from 'babel-preset-es2015-rollup';
console.log(JSON.stringify(preset));
{"plugins":[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,[null,{"async":false,"asyncGenerators":false}],null]}
error:
babel({
        sourceMaps: true,
        presets: [ preset ],
        babelrc: false
      })
must
presets:[{string},{string}]    eg: presets: ['es2015-rollup'],

TypeError: Error transforming /Users/tusm/github/backbone.marionette-master/src/backbone.marionette.js with 'babel' plugin: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.dirname (path.js:1326:5)
    at /Users/tusm/github/backbone.marionette-master/node_modules/babel-core/lib/transformation/file/options/option-manager.js:353:36
    at /Users/tusm/github/backbone.marionette-master/node_modules/babel-core/lib/transformation/file/options/option-manager.js:375:22
    at Array.map (native)
    at OptionManager.resolvePresets (/Users/tusm/github/backbone.marionette-master/node_modules/babel-core/lib/transformation/file/options/option-manager.js:364:20)
    at OptionManager.mergePresets (/Users/tusm/github/backbone.marionette-master/node_modules/babel-core/lib/transformation/file/options/option-manager.js:348:10)
    at OptionManager.mergeOptions (/Users/tusm/github/backbone.marionette-master/node_modules/babel-core/lib/transformation/file/options/option-manager.js:307:14)
    at OptionManager.init (/Users/tusm/github/backbone.marionette-master/node_modules/babel-core/lib/transformation/file/options/option-manager.js:465:10)
    at File.initOptions (/Users/tusm/github/backbone.marionette-master/node_modules/babel-core/lib/transformation/file/index.js:194:75)

**Comment by rafde** [comment]
I think you want to use /Users/tusm/github/backbone.marionette-master/lib/backbone.marionette.js

**Comment by paulfalgout** [comment]
Closing for now.  If this is still an issue we can re-open.

**Comment by paulfalgout** [comment]
Ok I know what this is.  If you do a npm i on node 6, things break.

Related https://github.com/marionettejs/backbone.marionette/issues/3199
